// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ2070fO-HBomZGmfcyJuI5ms1hDlm07Q',
    appId: '1:356984037284:web:94758f89d0c172d732ab31',
    messagingSenderId: '356984037284',
    projectId: 'myecoprinted-c6f72',
    authDomain: 'myecoprinted-c6f72.firebaseapp.com',
    storageBucket: 'myecoprinted-c6f72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3QW3Lfy5TWh3WVM1FIzfIJI8w9UjF9sQ',
    appId: '1:356984037284:android:c53d6d0c848762fe32ab31',
    messagingSenderId: '356984037284',
    projectId: 'myecoprinted-c6f72',
    storageBucket: 'myecoprinted-c6f72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqfZiawKHM6ay4MjgCN3gPg3OAqcuJO7c',
    appId: '1:356984037284:ios:8793b8db2d02800132ab31',
    messagingSenderId: '356984037284',
    projectId: 'myecoprinted-c6f72',
    storageBucket: 'myecoprinted-c6f72.appspot.com',
    iosBundleId: 'com.example.ncejAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqfZiawKHM6ay4MjgCN3gPg3OAqcuJO7c',
    appId: '1:356984037284:ios:8d17bb8fd10cc07e32ab31',
    messagingSenderId: '356984037284',
    projectId: 'myecoprinted-c6f72',
    storageBucket: 'myecoprinted-c6f72.appspot.com',
    iosBundleId: 'com.example.ncejAdmin.RunnerTests',
  );
}
